export const GET_PROFESSIONALS = "GET_PROFESSIONALS";
export const GET_CLIENTS = "GET_CLIENTS";
export const GET_SERVICES = "GET_SERVICES";
export const ADD_NEW_APPOINTMENT = "ADD_NEW_APPOINTMENT";


